[project]
name = "fastapi-mlmodel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.116.0",
    "pandas>=2.3.1",
    "scikit-learn==1.6.1",
    "streamlit>=1.46.1",
]
